### ISSUE TITLE
More Documentation

### ISSUE THREAD

**Issue by new-gen23** [dirkjanm/mitm6#22]
The PNPT certification uses this tool for the training. However, they do not mention how to use the aclpwn-20211219-144804.restore to restore the modified ACL. It might be that I am blind, but I couldn't find any comment or reference in your readme. 

This would really be helpful to clean up training environments. Otherwise, an admin might use this tool for testing and accidentally leave a vulnerable ACL on his DC.

**Comment by dirkjanm** [comment]
Modification of ACLs is done by ntlmrelayx and is not part of this project. The documentation you're looking for is in the aclpwn wiki here: https://github.com/fox-it/aclpwn.py/wiki/Restoring
